apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l2j8clfyi-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:7538ee8f352c1dbe6e0bd46ce394fcfe8e17dde4@sha256:33e9199c4cc3ded45073a5c5bd904509acb9c0dc7435d57fc3c2b11ed54d5198
          name: container-image
